### ISSUE TITLE
wat.js Test Issue

### ISSUE THREAD

**Issue by piper88** [codefellows-seattle-301d7/00-test-repo-demo#3]
### What is the expected result?

ex: What are you trying to accomplish?
Trying to practice creating github issues
### What is the actual result?

ex: What are you seeing, or what is happening?
I'm not sure this is the right place to be creating the Issue, as I didn't see a template appear to fill in. (as stated in the instructions)
### If there is an error message, what is the error message?

ex: Uncaught Reference Error: $ is not defined.
No error message.
### What steps have you taken to address the problem?

First I reread the instructions several times.
Then I tried to implement them.
### Please check these boxes after entering a title and clicking "Submit new issue":

 [X] I have entered the filename and the high-level problem as the title of this issue. 
 [X] I have answered all four of the above questions, and have ensured that the Preview tab looks good.
 [X] I have not been able to work through the issue after 15 minutes.

**Comment by patci-zz** [comment]
Well done! Apologies for the confusion - all issues are through the orange-ish icon at the top of the readme.md file.
